title: Arbain Nawawi
description: Syarah Arbain Nawawi oleh Ibn Daqiq
baseurl: "/arbain-nawawi" # the subpath of your site, e.g. /blog
url: "https://bagustris.github.io/arbain-nawawi" # the base hostname & protocol for your site

theme: jekyll-theme-primer

# Build settings
markdown: kramdown
highlighter: rouge

# Include custom CSS
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Ensure GitHub Pages uses `jekyll` gem
github:
  is_project_page: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - fonts