title: Arbain Nawawi
description: Syarah Arbain Nawawi oleh Ibn Daqiq
baseurl: "/arbain-nawawi" # the subpath of your site, e.g. /blog
url: "https://bagustris.github.io/arbain-nawawi" # the base hostname & protocol for your site

remote_theme: bagustris/primer2-theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Search configuration
search:
  enabled: true

# Ensure GitHub Pages uses `jekyll` gem
github:
  is_project_page: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - assets/fonts